let age=25;
console.log(age);
age=30;
console.log("after reassign"+age);
//let age=35;
//console.log(age);
var name="Anu";
console.log(name);
name="Arun";
console.log("after reassign"+name);
var name="Anju";
console.log("after redeclare"+name);
const country="India";
//nodecountry="USA";
let country="Oman";
console.log(country);